### ISSUE TITLE
where to pass partition Key in PubSub using dapr client ?

### ISSUE THREAD

**Issue by NitishGawde** [dapr/dotnet-sdk#425]
await daprClient.PublishEventAsync("pubsub", "Topic", "Message");

where to pass the partition key??
there no overload method for passing metadata(partition key)

**Comment by yaron2** [comment]
Hi, when using pub/sub there is no need to specify a partition key.

**Comment by NitishGawde** [comment]
@yaron2 Thanks for Reply. I am using Kafka for PubSub there are some cases where I need to maintain the order of the messages without a partition key Kafka can't guarantee the order of the messages.

**Comment by msfussell** [comment]
@NitishGawde. If you are wanting to include a partition key as a metadata flag for Kafka for PubSub, this would be added into the Kafka component in the Dapr components contrib repo. The partitioning is not set in the client API. If this is what you are trying to achieve then we can move this issue to the components contrib repo

**Comment by NitishGawde** [comment]
@msfussell , **Yes** 👍

**Comment by rynowak** [comment]
We need to add support metadata to pub/sub

**Comment by rynowak** [comment]
This was addressed by https://github.com/dapr/dotnet-sdk/pull/542 - we now have support for passing metadata in pub/sub calls.

**Comment by Alex69rus** [comment]
Hi all!
I faced the same issue, but I'm using the
```csharp
DaprClient.BulkPublishEventAsync(
            string pubsubName,
            string topicName,
            IReadOnlyList<TValue> events,
            Dictionary<string, string> metadata = default,
            CancellationToken cancellationToken = default)
```
And this method doesn't support dedicated partitionKey for each message. Only the same key one for all the messages.

@rynowak this fix didn't solve the issue for bulk publish, because each message should have it's own `partitionKey`

Does anyone know how can I solve my issue?
